#------------------------------------------------------------
# NIST CTCMS Slurm
#------------------------------------------------------------

# Cluster host and scheduler options: the defaults come from
# Graham at Compute Canada, running Slurm. Other options can
# be found in the library of snippets,
# `_includes/snippets_library`. To use one, replace options
# below with those in `_config_options.yml` from the
# library. E.g, to customise for Cirrus at EPCC, running
# Slurm, we could replace the options below with those from
#
# _includes/snippets_library/EPCC_Cirrus_slurm/_config_options.yml
#
# If your cluster is not represented in the library, please
# copy an existing folder, rename it, and customize for your
# installation. Remember to keep the leading slash on the
# `snippets` variable below!
---
snippets: "/snippets_library/LLNL_Pascal_slurm"

local:
  prompt: "[user@laptop ~]$"
  bash_shebang: "#!/usr/bin/bash"

remote:
  name: "pascal83"
  login: "pascal.nist.gov"
  host: "quartz"
  node: "pascal17"
  location: "Lawrence Livermore National Laboratory"
  homedir: "/g/g0/"
  user: "yourUsername"
  prompt: "yourUsername@pascal83"
  bash_shebang: "#!/bin/bash"

sched:
  name: "Slurm"
  submit:
    name: "sbatch"
    options: "--partition=pvis"
  queue:
    debug: "pdebug"
    testing: "pvis"
  status: "squeue"
  flag:
    user: "-u yourUsername"
    interactive: ""
    histdetail: "--format=JobName,Submit,Start,State,ReqCPUS,Reserved,Elapsed,MaxRSS -j"
    name: "-J"
    time: "-t"
    queue: "-p"
    partition: "-p pdebug"
  del: "scancel"
  interactive: "srun"
  info: "sinfo"
  comment: "#SBATCH"
  hist: "sacct -u yourUsername"
  hist_filter: ""

episode_order:
  - 10-hpc-intro
  - 11-connecting
  - 12-cluster
  - 13-scheduler
  - 14-environment-variables
  - 16-transferring-files
  - 17-parallel
  - 18-resources
  - 19-responsibility
