# UCL, University College London: Myriad + SGE
snippets: "/snippets_library/Unicamp_Cenapad_PBS"

local:
  prompt: "[user@laptop ~]$"

remote:
  name: "CENAPAD"
  login: "cenapad.unicamp.br"
  node: lovelace
  location: "UNICAMP"
  homedir: "/home/lovelace/proj/projeto"
  user: "yourUsername"
  prompt: "[yourUsername@lovelace ~]$ "
  bash_shebang: "#!/bin/bash -l"

sched:
  name: "PBS"
  submit:
    name: "qsub"
    options: "-q testes"
    iopt: ""
  status: "qstat"
  flag:
    user: "-u yourUsername"
    interactive: "-l mem=512M,h_rt=2:00:00"
    name: "-N"
    histdetail: "-j"
    time: "-l h_rt="
    queue: "-q"
  del: "qdel"
  interactive: "qsub -I"
  info: "pbsnodes -aSj"
  jobs: "qstat -a"
  queue: "qstat -Q"
  comment: "#PBS "
  hist: ""
  hist_filter: ""
  bash_shebang: "#!/bin/bash -l"

episode_order:
  - 10-hpc-intro
  - 11-connecting
  - 12-cluster
  - 13-scheduler
  - 14-environment-variables
  - 15-modules
  - 16-transferring-files
  - 17-parallel
  - 18-resources
  - 19-responsibility
